# Generated by Django 3.1.1 on 2020-12-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchTAGS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=80),
        ),
    ]
