# Generated by Django 3.1.1 on 2020-12-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchPRODUCTS', '0005_auto_20201209_1257'),
        ('marchTAGS', '0003_auto_20201223_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, to='marchPRODUCTS.Product'),
        ),
    ]
