# Generated by Django 3.1.5 on 2021-02-07 07:21

from django.db import migrations, models
import marchSITEINFO.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('sender', models.CharField(max_length=50, verbose_name='نام')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200, verbose_name='ادرس')),
                ('phone', models.CharField(max_length=25, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('companyName', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('companyLogo', models.FileField(upload_to=marchSITEINFO.models.media_upload_path, verbose_name='لوگو (320 x 350)')),
                ('aboutUsTxt', models.TextField(verbose_name='متن درباره ما')),
            ],
        ),
    ]
