# Generated by Django 3.1.5 on 2021-02-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchCOMMENTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
