# Generated by Django 3.1.5 on 2021-02-17 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marchCOMMENTS', '0004_comment_users_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='users_liked',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
