# Generated by Django 3.1.1 on 2020-11-27 22:51

from django.db import migrations, models
import marchPRODUCTS.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان یا اسم محصول', max_length=50)),
                ('description', models.TextField(default='توضیحات کامل', max_length=400)),
                ('price', models.IntegerField(default=0)),
                ('pic', models.ImageField(null=True, upload_to=marchPRODUCTS.models.media_upload_path)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
