# Generated by Django 3.1.1 on 2020-11-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchPRODUCTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caption',
            field=models.CharField(default='توضیحات کوتاه و مختصر', max_length=160),
        ),
    ]
