# Generated by Django 3.1.1 on 2020-12-09 09:27

from django.db import migrations, models
import marchPRODUCTS.models


class Migration(migrations.Migration):

    dependencies = [
        ('marchPRODUCTS', '0004_auto_20201129_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'عنوان', 'verbose_name_plural': 'محصول'},
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='caption',
            field=models.CharField(default='توضیحات کوتاه و مختصر', max_length=160, verbose_name='تعریف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='توضیحات کامل', max_length=400, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(null=True, upload_to=marchPRODUCTS.models.media_upload_path, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='عنوان یا اسم محصول', max_length=50, verbose_name='عنوان'),
        ),
    ]
