# Generated by Django 3.1.1 on 2020-12-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchPRODUCTS', '0005_auto_20201209_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='توضیحات کامل', max_length=800, verbose_name='توضیح'),
        ),
    ]
