# Generated by Django 3.1.5 on 2021-01-16 00:53

from django.db import migrations, models
import django.db.models.deletion
import marchPRODUCTS.models


class Migration(migrations.Migration):

    dependencies = [
        ('marchPRODUCTS', '0007_auto_20201227_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pic', models.ImageField(null=True, upload_to=marchPRODUCTS.models.media_gallery_upload_path, verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marchPRODUCTS.product')),
            ],
        ),
    ]
