# Generated by Django 3.1.5 on 2021-02-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchPRODUCTS', '0008_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
