# Generated by Django 3.1.1 on 2020-12-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marchCATEGORIES', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
