# Generated by Django 3.1.5 on 2021-01-26 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marchPRODUCTS', '0008_productgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('pay_date', models.DateTimeField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد های خرید کاربران',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderd_item_count', models.IntegerField(verbose_name='تعداد سفارش')),
                ('orderd_item_price', models.IntegerField(verbose_name='قیمت')),
                ('orderd_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marchPRODUCTS.product')),
                ('relative_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marchCart.cart')),
            ],
            options={
                'verbose_name': 'جزییات سبد',
                'verbose_name_plural': 'جزییات سبد ها',
            },
        ),
    ]
