# Generated by Django 3.1.5 on 2021-01-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchCart', '0002_auto_20210127_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='orderd_item_count',
            field=models.PositiveIntegerField(verbose_name='تعداد سفارش'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='orderd_item_price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
    ]
